### ISSUE TITLE
Adding a license file

### ISSUE THREAD

**Issue by Ethunxxx** [mistakia/nano-community#5]
Hi,
I believe this is a great project and would definitely be interested in contributing here and there. One thing I noticed, though, is that at the moment there is no license file specifying if/how the content can be reused, shared etc. 
Would you mind adding a license file?
Cheers!

**Comment by mistakia** [comment]
Thanks for starting an issue for this. 

That does indeed need to be tackled and I have been punting on it as I'm not too informed on what is most suitable. Feel free to chime in if you have any suggestions.

I'll start tackling that beast tomorrow.

**Comment by Ethunxxx** [comment]
Thank you for starting this project :-)!
As for the licenses, I believe it all depends on what your goals are. 

Feel free to check out [this guide](https://choosealicense.com/) on which open source license to choose. If you want it simple and permissive, I would suggest you go with the [MIT license](https://choosealicense.com/licenses/mit/).
